# Generated by Django 5.2.5 on 2025-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('exchange_rate', models.FloatField(default=1.0)),
            ],
        ),
    ]
