# Generated by Django 5.2.5 on 2025-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
