# Generated by Django 5.2.5 on 2025-08-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='_salary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
